@startuml
title Diagramme de cas d'utilisation raffiné de sprint 1

left to right direction

actor "Administrateur" as Admin

rectangle "Système" {
  
  usecase "S'authentifier" as UC_Auth
  usecase "se connecter" as UC_Login
  usecase "Se\ndeconnecter" as UC_Logout
  
  usecase "Consulter mon\nprofil" as UC_Profile
  
  usecase "Réinitialiser le\nmot de passe" as UC_ResetPwd
  usecase "Recoit un lien de\nréinitialisation par e-mail" as UC_EmailReset
  
  usecase "Modifier mon\ncompte" as UC_ModifyAccount
}

' Relations de l'administrateur avec les cas d'utilisation
Admin --> UC_Auth
Admin --> UC_Profile
Admin --> UC_ResetPwd
Admin --> UC_ModifyAccount

' Relations include et extend
UC_Auth ..> UC_Login : <<include>>
UC_Auth ..> UC_Logout : <<extend>>
UC_ResetPwd ..> UC_EmailReset : <<include>>

@enduml
